application:
  subdomain: cocookies
  background_task: true

  upstreams:
    - location: /
      backend: http://cocookies:8080/

services:
  cocookies:
    # docker.io/mariinkys/cocookies:0.1.3
    image: registry.lazycat.cloud/czyt/mariinkys/cocookies:ad3f66e33d8ea83b
    environment:
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=sqlite:/app/db/cocookies.db
    binds:
      - /lzcapp/var/db:/app/db
      - /lzcapp/var/uploads:/app/uploads
